parameters:
  redis_host: '%env(REDIS_HOST)%'
  redis_port: '%env(REDIS_PORT)%'
  circuit_breaker.failure_threshold: '%env(FAILURE_THRESHOLD)%'
  circuit_breaker.timeout_period: '%env(TIMEOUT_PERIOD)%'

services:
  Omidrezasalari\CircuitBreakerBundle\Service\RedisStorage:
    arguments:
      $host: '%redis_host%'
      $port: '%redis_port%'

  Omidrezasalari\CircuitBreakerBundle\Service\ApcuStorage: ~

  Omidrezasalari\CircuitBreakerBundle\Service\CircuitBreaker:
    arguments:
      $failureTreshHold: '%circuit_breaker.failure_threshold%'
      $timeoutPeriod: '%circuit_breaker.timeout_period%'
